spring:
  config:
    activate:
      on-profile: dev

# =====================
# Server Properties
# =====================
  port: ${PORT:8080}
  shutdown: graceful
  forward-headers-strategy: framework


---
spring:
  application:
    name: Car-Bazar
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariPool
      maximum-pool-size: 5
      minimum-idle: 1
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000
      initialization-fail-timeout: 60000
# =====================
# JPA / Hibernate
# =====================
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update   # âœ… production-safe
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
        format_sql: false
        generate_statistics: false

# =====================
# Spring Boot Startup
# =====================
  main:
    lazy-initialization: true
    allow-bean-definition-overriding: false

  jackson:
    serialization:
      INDENT_OUTPUT: false   # cleaner prod responses

# =====================
# Multipart
# =====================
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

# =====================
# Cloudinary
# =====================
cloudinary:
  cloud-name: ${CLOUDINARY_NAME}
  api-key: ${CLOUDINARY_KEY}
  api-secret: ${CLOUDINARY_SECRET}

# =====================
# User Service Config
# =====================
usersvc:
  otp:
    digits: 6
    expiry-minutes: 10
  rate-limit:
    resend-min-interval-seconds: 60
    max-sends-per-hour: 5
  jwt:
    secret: ${JWT_SECRET}
    issuer: Car-Bazar
    access-exp-minutes: 120
  channels:
    email-enabled: true
    sms-enabled: false

# =====================
# Management Endpoints
# =====================
management:
  endpoints:
    web:
      exposure:
        include= health,info:
  endpoint:
    health:
      show-details: when_authorized

BREVO_API_KEY: ${API_KEY}
MAIL_FROM: ${MAIL_FROM}
MAIL_FROM_NAME: Motor Bazaar


# =====================
# Logging
# =====================
logging:
  level:
    root: INFO
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    com.zaxxer.hikari: WARN
